import type { IPostDoc, IUserDoc } from "@/types";

import { placeholderAvatar, placeholderPostImage } from "@/lib/placeholderImages";

/** Shown when the live feed has no posts yet (matches reference layout). */
export const DEMO_POSTS = [
  {
    $id: "demo-post-1",
    $collectionId: "",
    $databaseId: "",
    $createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    $updatedAt: new Date().toISOString(),
    $permissions: [],
    caption:
      "Exploring the heart of the Amazon — every shade of green tells a story.",
    imageUrl: placeholderPostImage("amazon-1"),
    imageId: "demo-1",
    location: "America",
    tags: ["Amazon", "Forest", "Trees"],
    likes: [],
    creator: {
      $id: "demo-creator-1",
      $collectionId: "",
      $databaseId: "",
      $createdAt: "",
      $updatedAt: "",
      $permissions: [],
      name: "Hobbit",
      username: "hobbit",
      imageUrl: placeholderAvatar("hobbit"),
    },
  },
  {
    $id: "demo-post-2",
    $collectionId: "",
    $databaseId: "",
    $createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    $updatedAt: new Date().toISOString(),
    $permissions: [],
    caption: "Winter silence — snow, water, and a sky that never ends.",
    imageUrl: placeholderPostImage("snow-2"),
    imageId: "demo-2",
    location: "Canada",
    tags: ["Winter", "Nature", "Travel"],
    likes: ["demo-like"],
    creator: {
      $id: "demo-creator-2",
      $collectionId: "",
      $databaseId: "",
      $createdAt: "",
      $updatedAt: "",
      $permissions: [],
      name: "River",
      username: "river",
      imageUrl: placeholderAvatar("river"),
    },
  },
] as unknown as IPostDoc[];

export const DEMO_CREATORS = [
  {
    $id: "demo-user-jsm",
    $collectionId: "",
    $databaseId: "",
    $createdAt: "",
    $updatedAt: "",
    $permissions: [],
    name: "JavaScript Mastery",
    username: "JSMastery",
    email: "",
    imageUrl: placeholderAvatar("jsmastery"),
  },
  {
    $id: "demo-user-2",
    $collectionId: "",
    $databaseId: "",
    $createdAt: "",
    $updatedAt: "",
    $permissions: [],
    name: "Design Daily",
    username: "designdaily",
    email: "",
    imageUrl: placeholderAvatar("design-daily"),
  },
  {
    $id: "demo-user-3",
    $collectionId: "",
    $databaseId: "",
    $createdAt: "",
    $updatedAt: "",
    $permissions: [],
    name: "Code Craft",
    username: "codecraft",
    email: "",
    imageUrl: placeholderAvatar("codecraft"),
  },
  {
    $id: "demo-user-4",
    $collectionId: "",
    $databaseId: "",
    $createdAt: "",
    $updatedAt: "",
    $permissions: [],
    name: "Pixel Studio",
    username: "pixelstudio",
    email: "",
    imageUrl: placeholderAvatar("pixelstudio"),
  },
] as unknown as IUserDoc[];
